title: Meine Website
description: Willkommen auf meiner Seite
theme: minima

#Plugins
plugins:
-jekyll-feed
-jekyll-seo-tag

#Lokale Entwicklung
url: "http://localhost:4000"
baseurl: ""

#Build-Einstellungen
markdown: kramdown
permalink: pretty

# Dateien ausschließen
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - .bundle/