# Basis-Informationen
title: Meine Test-Website
description: Lokale Jekyll-Entwicklung
author: Dein Name

# Theme (mit korrektem Prefix!)
theme: jekyll-theme-cayman

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Lokale Entwicklung
url: "http://localhost:4000"
baseurl: ""

# Build-Einstellungen
markdown: kramdown
permalink: pretty

# Dateien ausschließen
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - .bundle/